CREATE TABLE attractions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);

CREATE TABLE ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attraction_id BIGINT NOT NULL,
    author VARCHAR(100) NOT NULL,
    score INTEGER NOT NULL CHECK (score BETWEEN 1 AND 5),
    CONSTRAINT fk_ratings_attraction FOREIGN KEY (attraction_id) REFERENCES attractions(id)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attraction_id BIGINT NOT NULL,
    author VARCHAR(100) NOT NULL,
    text VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_reviews_attraction FOREIGN KEY (attraction_id) REFERENCES attractions(id)
);

INSERT INTO attractions (name, category, latitude, longitude) VALUES
    ('Ленинский мемориал', 'MUSEUM', 54.3142, 48.4031),
    ('Дом-музей В.И. Ленина', 'MUSEUM', 54.3160, 48.3994),
    ('Бульвар Новый Венец', 'VIEWPOINT', 54.3148, 48.4020),
    ('Парк Победы', 'PARK', 54.3380, 48.3795),
    ('Ульяновский областной краеведческий музей', 'MUSEUM', 54.3145, 48.4044),
    ('Памятник букве Ё', 'ARCHITECTURE', 54.3136, 48.4055),
    ('Владимирский сад', 'PARK', 54.3167, 48.4018),
    ('Президентский мост', 'VIEWPOINT', 54.3612, 48.5110),
    ('Спасо-Вознесенский собор', 'ARCHITECTURE', 54.3089, 48.3948),
    ('Набережная реки Волги', 'VIEWPOINT', 54.3181, 48.4062);


INSERT INTO ratings (attraction_id, author, score) VALUES
    (1, 'Никита', 5),
    (2, 'Витя', 5),
    (3, 'Денис', 5),
    (4, 'Стас', 4),
    (5, 'Роберт', 5),
    (6, 'Глеб', 4);

INSERT INTO reviews (attraction_id, author, text, created_at) VALUES
    (1, 'Никита', 'Очень красивый музейный комплекс.', CURRENT_TIMESTAMP),
(3, 'Денис', 'Лучшее место для прогулки и фото.', CURRENT_TIMESTAMP),
(4, 'Стас', 'Большой парк, удобно гулять.', CURRENT_TIMESTAMP),
(6, 'Глеб', 'Необычный памятник, символ города.', CURRENT_TIMESTAMP);
